import argparse
import os
import sys
import json
import urllib.request
import urllib.error

# Add Test folder to path to import run_test
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.join(project_root, 'Test'))
from test_single import run_test

def init_args():
    parser = argparse.ArgumentParser(description='Debug Assistant for T&DS')
    parser.add_argument('--instance', required=True, help='Path to the source code (.cpp, .py)')
    parser.add_argument('--input', required=True, help='Path to the input data file (.in)')
    return parser.parse_args()

def load_settings():
    settings_path = os.path.join(project_root, 'setting_DNTS.json')
    try:
        with open(settings_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception as e:
        print(f"[Debug] Could not load settings: {e}")
        return {}

def generate_vscode_config(instance_path, input_path):
    vscode_dir = os.path.join(project_root, '.vscode')
    os.makedirs(vscode_dir, exist_ok=True)
    
    ext = os.path.splitext(instance_path)[1].lower()
    instance_name = os.path.basename(instance_path)
    instance_dir = os.path.dirname(os.path.abspath(instance_path))
    
    launch_path = os.path.join(vscode_dir, 'launch.json')
    tasks_path = os.path.join(vscode_dir, 'tasks.json')
    
    launch_config = {"version": "0.2.0", "configurations": []}
    
    if ext in ['.cpp', '.c++', '.cc']:
        exe_path = os.path.join(instance_dir, instance_name.split('.')[0] + ('.exe' if os.name == 'nt' else ''))
        
        # GDB configuration
        config = {
            "name": "(gdb) Launch T&DS Debug",
            "type": "cppdbg",
            "request": "launch",
            "program": exe_path,
            "args": [],
            "stopAtEntry": False,
            "cwd": instance_dir,
            "environment": [],
            "externalConsole": False,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": True
                }
            ],
            "preLaunchTask": "T&DS Build C++"
        }
        # If input_path is provided, standard GDB in VSCode cannot easily redirect stdin from a file directly in args.
        # But we can try `<` args or simply inform the user. Alternatively, Windows args could be `["<", input_path]`
        # Some debuggers support "stdio": ["input.in", "output.out", None] but cppdbg might not uniformly.
        # We'll just provide the config.
        
        launch_config["configurations"].append(config)
        
        # Create tasks.json for building
        tasks_config = {
            "version": "2.0.0",
            "tasks": [
                {
                    "type": "cppbuild",
                    "label": "T&DS Build C++",
                    "command": "g++",
                    "args": [
                        "-g",
                        instance_path,
                        "-o",
                        exe_path,
                        "-std=c++17"
                    ],
                    "options": {
                        "cwd": instance_dir
                    },
                    "problemMatcher": ["$gcc"],
                    "group": {
                        "kind": "build",
                        "isDefault": True
                    },
                    "detail": "Generated by T&DS Debugger."
                }
            ]
        }
        with open(tasks_path, 'w', encoding='utf-8') as f:
            json.dump(tasks_config, f, indent=4)
            
    elif ext == '.py':
        config = {
            "name": "Python: T&DS Debug",
            "type": "python",
            "request": "launch",
            "program": instance_path,
            "console": "integratedTerminal",
            "args": [
                "<",
                input_path
            ]
        }
        launch_config["configurations"].append(config)
    
    # Merge with existing launch.json if it exists
    if os.path.exists(launch_path):
        try:
            with open(launch_path, 'r', encoding='utf-8') as f:
                existing_launch = json.load(f)
                existing_launch.setdefault("configurations", []).extend(launch_config["configurations"])
                launch_config = existing_launch
        except Exception:
            pass
            
    with open(launch_path, 'w', encoding='utf-8') as f:
        json.dump(launch_config, f, indent=4)
        
    print(f"[Debug] Generated VSCode configurations for {instance_path}")

def call_openai_api(api_key, model, prompt):
    url = "https://api.openai.com/v1/chat/completions"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}"
    }
    data = {
        "model": model,
        "messages": [
            {"role": "system", "content": "You are a helpful debugging assistant."},
            {"role": "user", "content": prompt}
        ]
    }
    
    try:
        req = urllib.request.Request(url, data=json.dumps(data).encode('utf-8'), headers=headers)
        with urllib.request.urlopen(req) as response:
            result = json.loads(response.read().decode('utf-8'))
            return result['choices'][0]['message']['content']
    except urllib.error.HTTPError as e:
        return f"OpenAI API HTTPError: {e.code} {e.reason} - {e.read().decode('utf-8')}"
    except Exception as e:
        return f"OpenAI API Error: {str(e)}"

def start_debug(instance, input_file):
    settings = load_settings()
    
    # Generate VSCode Config
    generate_vscode_config(instance, input_file)
    
    # Infer standard_file
    in_path, in_ext = os.path.splitext(input_file)
    std_file = None
    if in_ext == '.in':
        inferred = in_path + '.out'
        if os.path.exists(inferred):
            std_file = inferred
            
    print(f"[Debug] Running test case to see if it needs AI assistance...")
    result = run_test(instance, input_file, std_file, timeout=2.0)
    
    if result['status'] in ['Accepted', 'Success']:
        print("[Debug] The program passed the test. No AI assistance needed.")
        print("[Debug] You can now press F5 in VSCode to start debugging if you want to inspect execution.")
        return
        
    print(f"[Debug] Program failed with status: {result['status']}. Preparing AI assistance...")
    
    api_key = settings.get("openai_api_key", "")
    if not api_key:
        print("[Debug] No OpenAI API key found in setting_DNTS.json. AI assistance skipped.")
        return
        
    # Read source code
    with open(instance, 'r', encoding='utf-8') as f:
        code_content = f.read()
        
    # Construct error detail
    error_detail = result['message']
    
    if result['status'] == 'WrongAnswer':
        wrong_out_file = result.get('wrong_output_file')
        if wrong_out_file and os.path.exists(wrong_out_file):
            with open(wrong_out_file, 'r', encoding='utf-8') as f:
                wrong_content = f.read()
            with open(std_file, 'r', encoding='utf-8') as f:
                std_content = f.read()
            error_detail += f"\n\n--- Actual Output ---\n{wrong_content}\n--- Expected Output ---\n{std_content}"
            
    # Load prompt template from settings
    prompt_template = settings.get("ai_prompt", "Code:\n{code}\n\nError:\n{error}")
    prompt = prompt_template.replace("{code}", code_content).replace("{error}", error_detail)
    
    print("[Debug] Sending request to OpenAI...")
    model = settings.get("openai_model", "gpt-4o")
    ai_response = call_openai_api(api_key, model, prompt)
    
    print("\n" + "="*50)
    print("🤖 AI Debugging Suggestions")
    print("="*50)
    print(ai_response)
    print("="*50)

if __name__ == '__main__':
    args = init_args()
    start_debug(args.instance, args.input)
